[info]
address = "tree house road, mountain creek, large lake city, wide valley, planet"
city = "cloudy town"
country = "forgotten lands"
email = "random@placeholder.com"
firstname = "mystery"
github = "coderShadow"
lastname = "wanderer"
linkedin = "mysticPath"
middleinitial = "S"
middlename = "secret trail"
phonenum = "(+1) 123-456-7890"
postalcode = "XYZ 123"
province = "north peak"
summary = "exploring unknown territories, discovering unseen landscapes, venturing into the wilds of code and beyond. decoding mysteries of the universe, one line at a time."

[core]
items = ["algorithm puzzles", "quantum computations", "robotic maneuvers", "stellar navigation"]

[topqual]
items = [
  "fluent in Python and Rust",
  "contributor to open source worlds",
  "versed in many languages of the web",
  "deeper understanding of automated testing",
  "strategist for agile and waterfall approaches"
]

[[qual]]
title = "Magician Practices"
items = [
  "orchestrator of containers and services",
  "architect of microservices",
  "creator of the universes of code and beyond"
]

[[exp]]
position = "Technical Assistant"
organization = "mystical church"
location = "mystical lands"
datestart = "2023-09"
dateend = "Current"
items = [
  "crafted magical solutions for system malfunctions",
  "connected realms via zoom portals",
  "tuned echoes of the sound systems",
  "wove clear communication webs between leaders"
]

[[exp]]
position = "Developer"
organization = "software guild"
location = "virtual university"
datestart = "2021-09"
dateend = "2021-12"
items = [
  "led quests for web application development",
  "charted maps through software design jungles",
  "crafted detailed guides of digital landscapes"
]

[[exp]]
position = "Developer"
organization = "network engineers"
location = "tower of technology"
datestart = "2021-09"
dateend = "2022-01"
items = [
  "forged links between data islands using C/C++",
  "designed protocols to whisper secrets across networks",
  "synchronized the flow of information across realms"
]


[[project]]
name = "mystical plugin"
position = "creator"
type= "pluto"
location = "wizard's library"
datestart = "2023-11"
dateend = "Current"
items = [
  "summoned images into texts of knowledge",
  "charted pathways for more than a thousand travelers",
  "wove spells to simplify magical toolkits"
]

[[project]]
type= "portal"
name = "portal enhancer"
position = "inventor"
location = "chamber of codes"
datestart = "2023-11"
dateend = "Current"
items = [
  "enchanted mirrors to reflect distant visions",
  "forged interfaces of power and simplicity",
  "reshaped tools for better conjuring"
]

[[project]]
type = "keychain"
name = "vault manager"
position = "architect"
datestart = "2022-07"
dateend = "Current"
items= [
  "crafted keychains for digital vaults",
  "summoned interfaces of enchantment",
  "linked realms with lines of command"
]

[[edu]]
degree = "Bachelor of Science in Magic"
institution = "castle of knowledge"
datestart = "2018-09"
dateend = "2023-06"
location = "high tower"
items = [
  "awarded the scholar of secret arts",
]
